name: Lint and Test

on:
  workflow_call:

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run ruff check
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/checkout@v2
      - run: pip install poetry
      - run: poetry install
      - run: poetry run pytest --mpl
